<ApplyInfo>
    <GeneralInfo>
        <Md5Value></Md5Value>
        <PlateformCode>${ROOT.code}</PlateformCode>
        <UUID>d83a011a-958d-4310-a51b-0fb3a4228ef5</UUID>
    </GeneralInfo>
    <PolicyInfos>
        <PolicyInfo>
            <SerialNo>1</SerialNo>
            <RiskCode>EAK</RiskCode>
            <OperateTimes>2017-11-15 16:57:36</OperateTimes>
            <StartDate>2018-12-28</StartDate>
            <EndDate>2019-12-27</EndDate>
            <StartHour>0</StartHour>
            <EndHour>24</EndHour>
            <SumAmount>50000.00</SumAmount>
            <SumPremium>30</SumPremium>
            <ArguSolution>1</ArguSolution>
            <Quantity>1</Quantity>
            <RationPlan>
                <RationType>EAK3502059</RationType>
                <quantity>4</quantity>
            </RationPlan>
            <Applicant>
                <AppliName>丁宏翔</AppliName>
                <AppliIdType>01</AppliIdType>
                <AppliIdNo>510231196406190012</AppliIdNo>
                <SendSMS>N</SendSMS>
                <AppliIdMobile>13901292436</AppliIdMobile>
                <AppliIdEmail>zhangyudong@sinosoft.com.cn</AppliIdEmail>
                <AppliIdentity>0</AppliIdentity>
            </Applicant>
            <Insureds>
                <Insured>
                    <InsuredSeqNo>1</InsuredSeqNo>
                    <InsuredName>丁宏翔</InsuredName>
                    <InsuredIdType>01</InsuredIdType>
                    <InsuredIdNo>510231196406190012</InsuredIdNo>
                    <InsuredBirthday>1964-06-19</InsuredBirthday>
                    <InsuredSex>1</InsuredSex>
                </Insured>
            </Insureds>
        </PolicyInfo>
    </PolicyInfos>
</ApplyInfo>	