<INSUREQRET>
    <xtpf_job>
        <xtpf_control>
            <select_page_by_user>no</select_page_by_user>
        </xtpf_control>
    </xtpf_job>
    <insert>
        <Form type="xdp">
            <name>${insert.From.name}</name>
            <visable>${insert.From.visable}</visable>
            <printable>${insert.From.printable}</printable>
            <package>${insert.From.package}</package>
        </Form>
    </insert>
    <MAIN>
        <FILE_ID>${MAIN.FILE_ID}</FILE_ID>
        <PRI_KEYWORD>${MAIN.PRI_KEYWORD}</PRI_KEYWORD>
        <BUSINESS_SOURCE/>
        <BUSINESS_MODE>${MAIN.BUSINESS_MODE}</BUSINESS_MODE>
        <PRINT_DATE>${MAIN.PRINT_DATE}</PRINT_DATE>
        <BRANCH_ID>${MAIN.BRANCH_ID}</BRANCH_ID>
    </MAIN>
    <POLICY_INFO>
        <BASE>
        <EMAIL_ATTACH_FLAG>${POLICY_INFO.EMAIL_ATTACH_FLAG}</EMAIL_ATTACH_FLAG>
        <INVOICE_FLAG>${POLICY_INFO.INVOICE_FLAG}</INVOICE_FLAG>
        <INVOICE_URL>${POLICY_INFO.INVOICE_URL}</INVOICE_URL>
        <INSURANCE_TYPE>${POLICY_INFO.INSURANCE_TYPE}</INSURANCE_TYPE>
        <SOCIAL_SECURITY>${POLICY_INFO.SOCIAL_SECURITY}</SOCIAL_SECURITY>
        <DETAILED_LIST>${POLICY_INFO.DETAILED_LIST}</DETAILED_LIST>
        <TITLE>${POLICY_INFO.TITLE}</TITLE>
        <BZ_CODE>CG0021601</BZ_CODE>
        <BRANCH_CODE>0101030000</BRANCH_CODE>
        <CONTACT_TEL></CONTACT_TEL>
        <CONTACT_EMAIL></CONTACT_EMAIL>
        <PRODUCT_NAME>惠享e家 家庭医疗保险</PRODUCT_NAME>
        <EFFECTIVE_DATE>2019年06月18日</EFFECTIVE_DATE>
        <MEMBER_NO>M1900810342</MEMBER_NO>
        <C_PLY_NO>P199920190101E1006541</C_PLY_NO>
        <C_APP_NME>江河</C_APP_NME>
        <C_APP_CERT_TYPE>居民身份证</C_APP_CERT_TYPE>
        <C_APP_CERT_NO>110101198001010598</C_APP_CERT_NO>
        <C_APP_TEL>13641235100</C_APP_TEL>
        <C_APP_EMAIL>1170700869@qq.com</C_APP_EMAIL>
        <C_INSRNT_RELATIONSHIP>子女,配偶,子女</C_INSRNT_RELATIONSHIP>
        <C_APP_ADDR></C_APP_ADDR>
        <CONTACTS_NME>江河</CONTACTS_NME>
        <CONTACTS_TEL>13641235100</CONTACTS_TEL>
        <C_INSRNT_TOTAL_NO>3</C_INSRNT_TOTAL_NO>
        <C_INSRNT_MAIN_NO>1</C_INSRNT_MAIN_NO>
        <C_INSRNT_RELATED_NO>2</C_INSRNT_RELATED_NO>
        <T_PERIOD_START>2019年06月18日</T_PERIOD_START>
        <T_PERIOD_END>2020年06月17日</T_PERIOD_END>
        <C_INSRNT_AREA>中华人民共和国境内（不含港澳台）</C_INSRNT_AREA>
        <I_ADDR_POST>深圳市前海深港合作区前湾一路1号A栋201室 518052</I_ADDR_POST>
        <PAY_WAY>趸交</PAY_WAY>
        <REMARK></REMARK>
        <N_PRM_FLAG>Z</N_PRM_FLAG>
        <C_APPNT>1、被保险人首次或者非连续投保时，防癌保险等待期 90天，其他保险责任等待期为30天。等待期内，因疾病住院或门诊造成的医疗费用支出或罹患疾病等，属于除外责任。
            2、本保单的各项保险责任除防癌保险金以外，年累计免赔额1万元。
            3、以有社会医疗保险身份参保，但是未以社会医疗保险身份就诊并结算的，本产品按应赔付金额的60%进行赔付。
            4、全家共用保额，是指保单中约定的所有家庭成员共同享有本产品列明的带有全家共用标识的保险责任所对应的保额，每位家庭成员享有的最高保障额度为该项保险责任的保额，当累计赔付金额达到该项保险责任的约定保额时，该项保险责任对所有的被保险人终止。
        </C_APPNT>
        <C_DISPUTE>诉讼</C_DISPUTE>
        <N_PRM_ONE>玖佰伍拾伍元伍角</N_PRM_ONE>
        <N_PRM>955.50</N_PRM>
        <C_SERVER_TEL>400_919_0505</C_SERVER_TEL>
        <C_DEPT_URL>www.pubmi.org</C_DEPT_URL>
        <SALES_ORGANIZATION>众惠财产相互保险社营业总部_营业三部（创新）</SALES_ORGANIZATION>
        <ADDR_POST>北京市朝阳区东三环中路20号乐成中心A座7层 100022</ADDR_POST>
        <SALES_NAME>杨欣娜</SALES_NAME>
        <SALES_ID>0101030005</SALES_ID>
        <DATE_Y>2019</DATE_Y>
        <DATE_M>06</DATE_M>
        <DATE_D>17</DATE_D>
        <PROFESORT_FLAG>Y</PROFESORT_FLAG>
        <C_BENEFINFO>法定</C_BENEFINFO>
        <BENEFINFO_FLAG>Y</BENEFINFO_FLAG>
        <HEALTH_INFORM>1、被保险人职业均属于《众惠财产相互保险社职业分类表》中的1_3类人员
            2、被保险人过去1年内均未发现健康检查异常（如血液、超声、影像检查、内镜、病理检查等）,过去2年内均未发生住院或被要求进一步检查、手术或住院治疗。
            3、被保险人过去两年内均未发生投保人身保险或健康保险时被保险公司拒保、延期、加费或者附加相关条件承保的情况。
            4、被保险人目前或过往均未患有下列疾病：良、恶性肿瘤，白血病，2级或以上高血压（收缩压大于160mmHg，舒张压大于100mmHg），冠心病，心肌梗死，脑梗死，脑出血，风湿性心脏病，心功能不全二级以上，肾功能不全，肝炎，肝硬化，重型再障性贫血，系统性红斑狼疮，类风湿性关节炎，糖尿病，帕金森氏病，癫痫，精神病，先天性疾病，传染病，慢性阻塞性肺病、瘫痪。
            5、被保险人过去1年内均不存在下列症状：反复头痛、晕厥、胸痛、气急、紫绀、持续反复发热、抽搐、不明原因皮下出血点、咯血、反复呕吐、进食梗噎感或吞咽困难、呕血、浮肿、腹痛、黄疸、便血、血尿、蛋白尿、肿块、消瘦（体重减轻5公斤以上）。
            6、2周岁以下被保险人出生时体重均不低于2.5公斤，不属于早产，窒息，发育迟缓，脑瘫。
        </HEALTH_INFORM>
        <INSRNT_LISTS>
            <INSRNT_LIST>
                <INSRNT_INFO>
                    <C_INSRNT_CNM>子女</C_INSRNT_CNM>
                    <C_INSRNT_SEX>女</C_INSRNT_SEX>
                    <C_INSRNT_BIRTHDAY>1998年01月01日</C_INSRNT_BIRTHDAY>
                    <C_INSRNT_SECURITY>无</C_INSRNT_SECURITY>
                    <C_INSRNT_CERT_TYPE>护照</C_INSRNT_CERT_TYPE>
                    <C_INSRNT_CERT_NO>11964644</C_INSRNT_CERT_NO>
                    <C_RELATIONSHIP>子女</C_RELATIONSHIP>
                    <C_BENEFNAME></C_BENEFNAME>
                    <PROFE_SORT></PROFE_SORT>
                </INSRNT_INFO>
                <INSRNT_INFO>
                    <C_INSRNT_CNM>配偶</C_INSRNT_CNM>
                    <C_INSRNT_SEX>女</C_INSRNT_SEX>
                    <C_INSRNT_BIRTHDAY>1998年01月01日</C_INSRNT_BIRTHDAY>
                    <C_INSRNT_SECURITY>无</C_INSRNT_SECURITY>
                    <C_INSRNT_CERT_TYPE>护照</C_INSRNT_CERT_TYPE>
                    <C_INSRNT_CERT_NO>964444</C_INSRNT_CERT_NO>
                    <C_RELATIONSHIP>配偶</C_RELATIONSHIP>
                    <C_BENEFNAME></C_BENEFNAME>
                    <PROFE_SORT></PROFE_SORT>
                </INSRNT_INFO>
                <INSRNT_INFO>
                    <C_INSRNT_CNM>子女</C_INSRNT_CNM>
                    <C_INSRNT_SEX>女</C_INSRNT_SEX>
                    <C_INSRNT_BIRTHDAY>1998年01月01日</C_INSRNT_BIRTHDAY>
                    <C_INSRNT_SECURITY>无</C_INSRNT_SECURITY>
                    <C_INSRNT_CERT_TYPE>军官证</C_INSRNT_CERT_TYPE>
                    <C_INSRNT_CERT_NO>999664</C_INSRNT_CERT_NO>
                    <C_RELATIONSHIP>子女</C_RELATIONSHIP>
                    <C_BENEFNAME></C_BENEFNAME>
                    <PROFE_SORT></PROFE_SORT>
                </INSRNT_INFO>
            </INSRNT_LIST>
        </INSRNT_LISTS>
        </BASE>
        <PROD_LIST>
            <PROD_INFO>
                <PROD_PLAN></PROD_PLAN>
                <INSURED_NUM></INSURED_NUM>
                <RDR_INFO>
                    <PROD_NAME>惠享e家 家庭医疗保险</PROD_NAME>
                    <PROD_CNM>一般医疗保险金（全家共用保额）</PROD_CNM>
                    <N_COV_AMT>1500000.00</N_COV_AMT>
                    <N_PLAN_PREM>271.50</N_PLAN_PREM>
                    <DEDU_WAY>累计免赔</DEDU_WAY>
                    <DEDU_AMT>10000.00</DEDU_AMT>
                    <RATIO_PAYMENT>100%</RATIO_PAYMENT>
                </RDR_INFO>
            </PROD_INFO>
            <PROD_INFO>
                <PROD_PLAN></PROD_PLAN>
                <INSURED_NUM></INSURED_NUM>
                <RDR_INFO>
                    <PROD_NAME>惠享e家 家庭医疗保险</PROD_NAME>
                    <PROD_CNM>恶性肿瘤医疗保险金（全家共用保额）</PROD_CNM>
                    <N_COV_AMT>1500000.00</N_COV_AMT>
                    <N_PLAN_PREM>30.00</N_PLAN_PREM>
                    <DEDU_WAY>累计免赔</DEDU_WAY>
                    <DEDU_AMT>10000.00</DEDU_AMT>
                    <RATIO_PAYMENT>100%</RATIO_PAYMENT>
                </RDR_INFO>
            </PROD_INFO>
            <PROD_INFO>
                <PROD_PLAN></PROD_PLAN>
                <INSURED_NUM></INSURED_NUM>
                <RDR_INFO>
                    <PROD_NAME>惠享e家 家庭医疗保险</PROD_NAME>
                    <PROD_CNM>防癌保险金（全家共用保额）</PROD_CNM>
                    <N_COV_AMT>10000.00</N_COV_AMT>
                    <N_PLAN_PREM>17.00</N_PLAN_PREM>
                    <DEDU_WAY></DEDU_WAY>
                    <DEDU_AMT></DEDU_AMT>
                    <RATIO_PAYMENT>100%</RATIO_PAYMENT>
                </RDR_INFO>
            </PROD_INFO>
        </PROD_LIST>
    </POLICY_INFO>
    <Clauses>
        <Clause>
            <ClauseID>PUBMI006</ClauseID>
            <Clause_Name>《众惠财产相互保险社团体中高端医疗保险（2017款）条款》(众惠相互)(备_医疗保险)【2017】(主) 005号</Clause_Name>
            <hyperlink>http://website_10077367.file.myqcloud.com/clause/99/c74a3227_848f_4fb5_9319_d037530140b0.pdf
            </hyperlink>
        </Clause>
        <Clause>
            <ClauseID>PUBMI007</ClauseID>
            <Clause_Name>《众惠财产相互保险社团体防癌保险（2017款）条款》(众惠相互)(备_疾病保险)【2017】(主) 002号</Clause_Name>
            <hyperlink>http://website_10077367.file.myqcloud.com/clause/99/af64d21f_a5df_4f90_8bfd_ede88fe38c16.pdf
            </hyperlink>
        </Clause>
        <Clause>
            <ClauseID>PUBMI008</ClauseID>
            <Clause_Name>《众惠财产相互保险社附加共用保额保险（2017款）条款》(众惠相互)(备_普通意外保险)【2017】(附) 002号</Clause_Name>
            <hyperlink>http://website_10077367.file.myqcloud.com/clause/10/2fe88047_a701_4274_8ab9_4e621fd0eb19.pdf
            </hyperlink>
        </Clause>
        <Clause>
            <ClauseID>PUBMI009</ClauseID>
            <Clause_Name>《惠享e家 家庭医疗保险费率表》</Clause_Name>
            <hyperlink>http://website_10077367.file.myqcloud.com/clause/99/d6d2ec47_59fd_41d0_88ed_fce69ce62639.pdf
            </hyperlink>
        </Clause>
    </Clauses>
</INSUREQRET>